name: Add Package to Registry

on:
  repository_dispatch:
    types: [add-package]

jobs:
  add-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Generate GitHub App token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.HATCH_WORKFLOW_APP_ID }}
          private_key: ${{ secrets.HATCH_WORKFLOW_APP_PRIVATE_KEY }}
      
      - name: Install pip
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Hatch-Registry
        run: |
          pip install -r requirements.txt
          pip install .
      
      - name: Download package release
        run: |
          REPO="${{ github.event.client_payload.repository }}"
          TAG="${{ github.event.client_payload.release_tag }}"
          PACKAGE="${{ github.event.client_payload.package_name }}"
          VERSION="${{ github.event.client_payload.version }}"
          
          # Download the release asset
          curl -L -o ${PACKAGE}-${VERSION}.zip \
            -H "Authorization: token ${{ steps.generate-token.outputs.token }}" \
            https://api.github.com/repos/${REPO}/releases/tags/${TAG}/assets
      
      - name: Add package to registry
        run: |
          PACKAGE="${{ github.event.client_payload.package_name }}"
          VERSION="${{ github.event.client_payload.version }}"
          REPO="${{ github.event.client_payload.repository }}"
          
          hatch-registry add-package \
            --name ${PACKAGE} \
            --version ${VERSION} \
            --source-repo ${REPO} \
            --package-file ${PACKAGE}-${VERSION}.zip
      
      - name: Commit changes to registry
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add registry.json
          git commit -m "Add package ${{ github.event.client_payload.package_name }} v${{ github.event.client_payload.version }}"
          git push